export const LOGIN = "login"
export const REGISTER = "register"
export const DRAWER_NAVIGATOR = "drawer"
export const DASHBOARD = "dashboard"
export const MARKET = "market"
export const PORTFOLIO = "portfolio"
export const MINT = "mint"
export const ADMIN = "admin"