import {
  BASE_URL,
  URL_PREFIX,
  STORAGE_PATH,
  INSTAGRAM_API,
  INSTAGRAM_API_VERSION,
  INSTAGRAM_APP_ID,
  INSTAGRAM_SECRET_KEY,
  WEBSITE,
} from '@env';

export default {
  BASE_URL,
  URL_PREFIX,
  INSTAGRAM_API,
  INSTAGRAM_API_VERSION,
  INSTAGRAM_APP_ID,
  INSTAGRAM_SECRET_KEY,
  WEBSITE,
  STORAGE_PATH,
};
